server:
  port: 8081

spring:
  application:
    name: springcloud-provider

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/1811b?serverTimezone=Hongkong&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root

  #redis:
   # host: 192.168.18.129
   # port: 6379


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka


